services:
  jupyter:
    image: jupyter/base-notebook
    container_name: sprint_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    env_file:
      - .env
    command: "start-notebook.sh --ServerApp.token=''"
    deploy:
      resources:
        limits:
          memory: 11g
