services:
  jupyter:
    build: .  # 이 줄이 중요!
    # image: jupyter/base-notebook  # 이 줄 삭제 또는 주석처리
    container_name: sprint_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-12g}
    command: >
      sh -c "start-notebook.sh --ServerApp.token=''"