services:
  jupyter:
    image: jupyter/base-notebook
    container_name: sprint_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-16g}  # 기본값 12GB
    command: >
      sh -c "pip install -r /home/final_key/project/sprint_final_project/requirements.txt && 
             start-notebook.sh --ServerApp.token=''"
             